### ISSUE TITLE
CSRF attacks at /resetpassword

### ISSUE THREAD

**Issue by forierg4210** [s1155002037/shop03#2]
![default](https://cloud.githubusercontent.com/assets/10591715/7540471/95a3300c-f5e0-11e4-9f01-e33e9ce42997.JPG)
Since no test account is provided, I can only talk about the codes without illustration
If A has logged in, B can just perform csrf and post a form to /resetpassword
Since there is no checking about the old password or token, the password will just be replaced by the sent password.
Suggestion: add checking of token and apply csrf in the post function.

**Comment by s1155002037** [comment]
This resetpassword is used for securely changing password through email instead of change password for logged user. The request link includes email of user and reset token. Without opening the link through the email, no CSRF can performed successfully since the attacker has no idea about the reset token.

**Comment by forierg4210** [comment]
The token validation in the get request is bypassed as I don't need to get your form.
Since there is no validation of token in the post part, I can just compose a form to post to your link.

**Comment by s1155002037** [comment]
If you want to bypass the get request, then the token is not validated and because the user email is saved into the req.session only after the validation, you will have no idea about the user's email. Since this is reset password from email, there will be no cookie information if you bypass the get request part, so you can't compose the correct form.
![screen shot 2015-05-12 at 11 12 47](https://cloud.githubusercontent.com/assets/10591086/7579553/2c7709ae-f898-11e4-8584-6b2cd790d4dd.png)

**Comment by forierg4210** [comment]
I am sorry for missing that part.
But still, if the user entered the get part, the email will be set.
There is still time for the attacker to perform csrf to post the form with req.session.reset.email set just before the user submits.

**Comment by hkop2002** [comment]
[TA comment] Valid security issue, but didn't illustrate the possible situation correctly. 
As the store do not provide change email function, user B still can not get the email and further, the token. And anyone that can get the token can reset the password.
Based on above, I consider this issue as invalid.
